exports.Token = "NzkwOTM3MDI0OTQxMTI5NzU5.X-H3gQ.q2zfRr29gKf0HhWzHhGim3HX0xw"; //Bot Token - Important
exports.Owner = "767726828311543820"; //Bot Owner ID - Important
exports.Default_Prefix = "!"; //Bot Default Prefix (Examples: A!, !)- Important
exports.Color = "RANDOM"; //Bot All Embeds Color - Use CAPS For Name (Examples: BLUE, RANDOM) - Important
exports.Support = `https://discord.gg/MKwyk4qdeb`; //Support Server Link - Never Gonna Give You Up (If No Link Provided)
exports.Donate = ``; //https://www.youtube.com/channel/UCpLctSYrYYQm58ul219kMwg`; //Please Don't Change It, If You Want To Support Me <3
exports.Dashboard = ``;
exports.Mongo = "mongodb://localhost/dghbot";
exports.id = `790937024941129759`;//id bot
